<a href="https://colab.research.google.com/github/Ever1ck/bigdata1/blob/main/Ejercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importar NumPy:**

In [ ]:
import numpy as np

**1. Creación de Arrays:**

In [ ]:
#Crea un array unidimensional (vector) con 5 elementos enteros de tu elección

arreglo = np.array([2,4,5,7,9,5])
print(arreglo)

[2 4 5 7 9 5]


In [60]:
#Crea una matriz bidimensional (matriz) de tamaño 3x3 con valores enteros consecutivos.
arreglo2 = np.arange(1, 10).reshape(3, 3)

print(arreglo2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Utiliza la función np.zeros() para crear una matriz de tamaño 2x4 llena de ceros.
arreglo3 = np.zeros([2,4])
print(arreglo3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#Utiliza la función np.ones() para crear una matriz de tamaño 3x2 llena de unos.
arreglo4 = np.ones([3,2])
print(arreglo4)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#Utiliza la función np.random.randint() para crear una matriz de tamaño 4x4 con números enteros aleatorios entre 0 y 10.
arreglo5 = np.random.randint(0,10, size=[4,4])
print(arreglo5)

[[3 5 3 1]
 [9 2 2 8]
 [4 3 8 9]
 [8 1 5 2]]


**2. Acceso a Elementos:**

In [ ]:
#Accede al tercer elemento del vector creado en el paso 1.
elemento1 = arreglo[2]
print(elemento1)

5


In [ ]:
#Accede al elemento en la segunda fila y segunda columna de la matriz creada en el paso 1.
elemento2 = arreglo2[1][1]
print(elemento2)

5


**3. Propiedades de los Arrays:**

In [ ]:
#Utiliza el atributo ndim para verificar la cantidad de dimensiones de la matriz creada en el paso 1.
print(arreglo2.ndim)

2


In [ ]:
#Utiliza el atributo shape para obtener la forma de la matriz creada en el paso 1.
print(arreglo2.shape)

(3, 3)


In [ ]:
#Utiliza el atributo size para obtener el tamaño total de la matriz creada en el paso 1.
print(arreglo2.size)

9


**4. Operaciones Básicas:**

In [ ]:
#Suma dos matrices de tamaño 2x2 con valores aleatorios entre 0 y 10.
matriz1 = np.random.randint(0,10, size=[2,2])
matriz2 = np.random.randint(0,10, size=[2,2])
print(matriz1)
print(matriz2)
sumam = matriz1 + matriz2
print("la suma de la matriz 1 y 2 es: ",sumam)

[[8 8]
 [8 2]]
[[2 6]
 [5 3]]
la suma de la matriz 1 y 2 es:  [[10 14]
 [13  5]]


In [ ]:
#Multiplica dos matrices de tamaño 3x2 y 2x3 respectivamente.
matriz3 = np.random.randint(0,10, size=[3,2])
matriz4 = np.random.randint(0,10, size=[3,2])
matriz5 = np.random.randint(0,10, size=[2,3])
matriz6 = np.random.randint(0,10, size=[2,3])
print(matriz3)
print(matriz4)
multi1 = matriz3 * matriz4
multi2 = matriz5 * matriz6

print("la multiplicacion de la matriz 3 y 4 es: ",multi1)
print("la multiplicacion de la matriz 5 y 6 es: ", multi2)


[[6 4]
 [5 4]
 [9 9]]
[[2 1]
 [0 3]
 [5 7]]
la multiplicacion de la matriz 3 y 4 es:  [[12  4]
 [ 0 12]
 [45 63]]
la multiplicacion de la matriz 5 y 6 es:  [[ 8  9  0]
 [49  0 81]]


In [41]:
#Divide una matriz de tamaño 2x2 por otra matriz de tamaño 2x2,
#utilizando tanto la división por elementos como la multiplicación por la inversa.

matriz7 = np.random.randint(0,10, size=[2,2])
matriz8 = np.random.randint(0,10, size=[2,2])
division1 = matriz7 / matriz8
print("la division es: ", division1)

inversa = np.linalg.inv(matriz8)
multiplicacion_inversa = np.dot(matriz7, matriz8)
print("la multiplicacion inversa es: ", multiplicacion_inversa)

la division es:  [[0.25 1.  ]
 [0.   3.  ]]
la multiplicacion inversa es:  [[76 16]
 [27  3]]


**5. Manipulación de Arrays:**

In [42]:
#Utiliza la función reshape() para convertir el vector creado en el paso 1
#en una matriz de tamaño 9x1.
reshape_arreglo = arreglo2.reshape([9,1])
print(reshape_arreglo)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [43]:
#Utiliza la función flatten() para convertir la matriz creada en el paso 1
#en un vector unidimensional.
flatten_arreglo = arreglo2.flatten()
print(flatten_arreglo)

[1 2 3 4 5 6 7 8 9]


**6. Operaciones Estadísticas:**

In [45]:
#Calcula la suma de todos los elementos de la matriz creada en el paso 1.
suma_elementos = np.sum(arreglo2)
print(suma_elementos)

45


In [50]:
#Calcula la media de cada fila de la matriz creada en el paso 1.
media = arreglo2[1].mean()
print(media)

5.0


**7. Indexación y Rebanado:**

In [54]:
#Imprime la primera fila de la matriz creada en el paso 1.
print(arreglo2[0])

[1 2 3]


In [55]:
#Imprime las primeras dos columnas de la matriz creada en el paso 1.
print(arreglo2[:, :2])

[[1 2]
 [4 5]
 [7 8]]


**8. Ejercicio Adicional:**

In [58]:
#Define una matriz de tamaño 4x4 con valores aleatorios.
matriz4x4 = np.random.rand(4, 4)
print(matriz4x4)

[[0.72253624 0.45204075 0.17772836 0.08785402]
 [0.0695596  0.53582081 0.18929391 0.65092406]
 [0.94894491 0.19038511 0.41151431 0.62993275]
 [0.97654268 0.72123789 0.44407894 0.88504611]]


In [59]:
#Escribe un código para encontrar el valor máximo y mínimo de la matriz, así como su posición.
# Imprimimos la matriz
print("Matriz:")
print(matriz4x4)

# Encontramos el valor máximo y su posición
max_value = np.max(matriz4x4)
max_position = np.unravel_index(np.argmax(matriz4x4), matriz4x4.shape)

# Encontramos el valor mínimo y su posición
min_value = np.min(matriz4x4)
min_position = np.unravel_index(np.argmin(matriz4x4), matriz4x4.shape)

# Imprimimos los resultados
print("\nValor máximo: ", max_value)
print("Posición del valor máximo: ", max_position)

print("\nValor mínimo: ", min_value)
print("Posición del valor mínimo: ", min_position)

Matriz:
[[0.72253624 0.45204075 0.17772836 0.08785402]
 [0.0695596  0.53582081 0.18929391 0.65092406]
 [0.94894491 0.19038511 0.41151431 0.62993275]
 [0.97654268 0.72123789 0.44407894 0.88504611]]

Valor máximo:  0.9765426838104997
Posición del valor máximo:  (3, 0)

Valor mínimo:  0.06955960354335955
Posición del valor mínimo:  (1, 0)
